name: Update Documentation

permissions:
 contents: write

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build HTML documentation
      run: |
        sphinx-build -b html doc_sphinx/source doc_sphinx/build/html

    - name: Add and commit documentation changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git config advice.addIgnoredFile false
        git add -A
        git commit -m "Update documentation" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}