name: Update Documentation

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx sphinx-autodoc-typehints python-docs-theme wheel setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist bdist_wheel || (echo "Failed to build wheel package" && exit 1)
        pip install dist/loggingpython-*-py3-none-any.whl || (echo "Failed to install wheel package" && exit 1)

    - name: Build HTML documentation
      run: |
        sphinx-build -b html doc_sphinx/source doc_sphinx/build

    - name: Add and commit documentation changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git commit -m "Update documentation" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}